# server configuration
server:
  port: 9527
  contextPath: /
  timeout: 10
  host:

# grpc configuration
grpc:
  jwt-address: '127.0.0.1:9528'
  auth-address: '127.0.0.1:9529'

# system configuration
system:
  db-type: 'mysql'
  use-multipoint: false
  env: 'public'  # Change to "develop" to skip authentication for development mode

# gateway configuration
gateway:
  ignoredPatterns: [ base, gateway, js, css ]
  sensitiveHeaders: [Cookie]
  routers:
    base:
      path: /base/**
      serviceId: user
      stripPrefix: false
      url: http://127.0.0.1:8080
      timeout: 20
    user:
      path: /user/**
      serviceId: user
      stripPrefix: false
      url: http://127.0.0.1:8080
      timeout: 20
    gitbook:
      path: /gitchat/**
      url: https://gitbook.cn
      stripPrefix: false
      timeout: 5

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GIN-VUE-ADMIN]'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'qmPlus'
  username: 'root'
  password: '521207'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: ""

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# jwt configuration
jwt:
  signing-key: 'qmPlus'
  expires-time: 604800
  buffer-time: 86400